all:
	gcc -c op.c 
	gcc -o test test.c op.o -I/home/knw/Desktop/Study/git/study/TDD/simple_pomodoro/step9/install/include -L/home/knw/Desktop/Study/git/study/TDD/simple_pomodoro/step9/install/lib -lcunit
	gcc -o main main.c op.o
