all:
	gcc -o example example.c -I/home/knw/Desktop/Study/git/study/TDD/simple_pomodoro/step7/CUnit/install/include -L/home/knw/Desktop/Study/git/study/TDD/simple_pomodoro/step7/CUnit/install/lib -lcunit
